project:
  type: website
  output-dir: docs

website:
  title: "Statistical Insights"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - bayesian-divination.qmd
      - simulations.qmd
      - about.qmd
    right:
      - icon: github
        href: http://github.com/paul-kimani/Journey-to-becoming-a-Statistical-Prophet
  sidebar:
    style: "docked"

format:
  html:
    theme:
      - litera # Clean, modern Bootstrap theme
    css: styles.css
    toc: true
    code-fold: true
    execute:
      echo: true
      warning: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&family=Fira+Mono&display=swap">