project:
  type: website
  output-dir: docs

website:
  title: "Statistical Cosmos"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - bayesian-divination.qmd
      - simulations.qmd
      - stat_finance.qmd
      - about.qmd
    right:
      - icon: github
        href: http://github.com/paul-kimani/Journey-to-becoming-a-Statistical-Prophet
  sidebar:
    style: "docked"

format:
  html:
    theme:
      - litera
    css: styles.css
    toc: true
    code-fold: true
    execute:
      echo: true
      warning: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;600&family=JetBrains+Mono&display=swap">
          <canvas id="starfield" style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: -1;"></canvas>
          <script src="starfield.js"></script>